<?php

namespace ContainerERK0NfI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCriarAdminCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CriarAdminCommand' shared autowired service.
     *
     * @return \App\Command\CriarAdminCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CriarAdminCommand.php';

        $container->privates['App\\Command\\CriarAdminCommand'] = $instance = new \App\Command\CriarAdminCommand(($container->privates['Core\\UseCase\\Usuario\\RegistrarUsuario'] ?? $container->load('getRegistrarUsuarioService')));

        $instance->setName('usuario:criar-vitu');
        $instance->setDescription('Cria um usuário do tipo ADMIN via terminal.');

        return $instance;
    }
}
