<?php

namespace ContainerERK0NfI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrarUsuarioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Core\UseCase\Usuario\RegistrarUsuario' shared autowired service.
     *
     * @return \Core\UseCase\Usuario\RegistrarUsuario
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'UseCase'.\DIRECTORY_SEPARATOR.'Usuario'.\DIRECTORY_SEPARATOR.'RegistrarUsuario.php';

        return $container->privates['Core\\UseCase\\Usuario\\RegistrarUsuario'] = new \Core\UseCase\Usuario\RegistrarUsuario(($container->privates['App\\Repository\\UsuarioRepository'] ?? $container->load('getUsuarioRepositoryService')));
    }
}
