nelmio_api_doc:
    documentation:
        info:
            title: 'YouGift API'
            description: 'API REST para gestão de gift cards digitais'
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api/v1
