<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWw1cxxJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWw1cxxJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWw1cxxJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWw1cxxJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWw1cxxJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ww1cxxJ',
    'container.build_id' => '3f87ec04',
    'container.build_time' => 1748042134,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWw1cxxJ');
