<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHG4X8As\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHG4X8As/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHG4X8As.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHG4X8As\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHG4X8As\App_KernelDevDebugContainer([
    'container.build_hash' => 'HG4X8As',
    'container.build_id' => '7186b8f2',
    'container.build_time' => 1748407582,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHG4X8As');
