<?php

namespace ContainerXIXjIDV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QHDU7RoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qHDU7Ro' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qHDU7Ro'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
        ], [
            'repo' => '?',
        ]);
    }
}
