<?php

namespace ContainerXIXjIDV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AuthController' shared autowired service.
     *
     * @return \App\Controller\AuthController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AuthController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'UseCase'.\DIRECTORY_SEPARATOR.'Usuario'.\DIRECTORY_SEPARATOR.'AutenticarUsuario.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Infra'.\DIRECTORY_SEPARATOR.'JwtTokenService.php';

        $container->services['App\\Controller\\AuthController'] = $instance = new \App\Controller\AuthController(new \Core\UseCase\Usuario\AutenticarUsuario(($container->privates['App\\Repository\\UsuarioRepository'] ?? $container->load('getUsuarioRepositoryService')), new \App\Infra\JwtTokenService(($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')))), ($container->privates['Core\\UseCase\\Usuario\\RegistrarUsuario'] ?? $container->load('getRegistrarUsuarioService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\AuthController', $container));

        return $instance;
    }
}
