<?php

namespace ContainerXIXjIDV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioControllerviewUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qHDU7Ro.App\Controller\UsuarioController::viewUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qHDU7Ro.App\\Controller\\UsuarioController::viewUser()'] = ($container->privates['.service_locator.qHDU7Ro'] ?? $container->load('get_ServiceLocator_QHDU7RoService'))->withContext('App\\Controller\\UsuarioController::viewUser()', $container);
    }
}
