# Generated by Django 5.2.1 on 2025-05-19 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvv_encrypted', models.TextField()),
                ('card_number_encrypted', models.TextField()),
                ('card_holder_name', models.CharField(max_length=255)),
                ('expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['card_holder_name'],
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Aguardando Pagamento'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Gift Card Order',
                'verbose_name_plural': 'Gift Card Orders',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api_app.giftcard')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_app.giftcardorder')),
            ],
            options={
                'verbose_name': 'Gift Card Order Item',
                'verbose_name_plural': 'Gift Card Order Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='api_app.giftcard')),
            ],
            options={
                'verbose_name': 'Gift Card Value',
                'verbose_name_plural': 'Gift Card Values',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='SaleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('card', 'Cartão'), ('pix', 'Pix')], default='credit', max_length=10)),
                ('transaction_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_history', to='api_app.bankaccount')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_history', to='api_app.giftcardorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_history', to='api_app.user')),
            ],
            options={
                'verbose_name': 'Sale History',
                'verbose_name_plural': 'Sale Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='api_app.giftcard')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='api_app.giftcardorderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_serials', to='api_app.user')),
            ],
            options={
                'verbose_name': 'Gift Card Serial',
                'verbose_name_plural': 'Gift Card Serials',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='giftcardorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api_app.user'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='api_app.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api_app.usergroup'),
        ),
    ]
