# Generated by Django 5.2.1 on 2025-05-21 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardorderitem',
            name='gift_card_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.giftcardvalue'),
        ),
    ]
