# Generated by Django 5.2.1 on 2025-05-21 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_giftcardorderitem_gift_card_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardorderitem',
            name='gift_card_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.giftcardvalue'),
        ),
    ]
