app.swagger_ui:
    path: /api/v1
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, require_auth: false }

app.swagger:
    path: /api/v1/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, require_auth: false }

